name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm config set fund false
          npm config set audit false
          npm ci --no-audit --no-fund || npm install --no-audit --no-fund

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          # Enable the Pages site if it has not been created yet
          enablement: true
          # Explicit token (defaults to GITHUB_TOKEN but we pass it for clarity)
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine base path for Pages
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "CANOPY_BASE_PATH=" >> $GITHUB_ENV
          else
            echo "CANOPY_BASE_PATH=/$REPO_NAME" >> $GITHUB_ENV
          fi

      - name: Build site
        env:
          # Optional: tune IIIF build performance in CI
          CANOPY_CHUNK_SIZE: "10"
          CANOPY_FETCH_CONCURRENCY: "6"
          # Optional: override collection in CI to reduce build time
          # CANOPY_COLLECTION_URI: https://iiif.io/api/cookbook/recipe/0032-collection/collection.json
        run: npm run build

      - name: Verify pages were generated
        run: node app/scripts/canopy-build.mjs --verify

      - name: Inspect build output
        run: |
          du -sh site || true
          ls -lah site || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
